
import React from 'react';
import { Ticket, MatchSelection, AppMode } from '../types';
import { ResponsiveContainer, PieChart, Pie, Cell, Tooltip } from 'recharts';
import { ShieldAlert, TrendingUp, Clock, MapPin, Globe, Layers, Sigma, Coins, Wallet, Landmark } from 'lucide-react';

interface TicketDisplayProps {
  ticket: Ticket;
}

const TicketDisplay: React.FC<TicketDisplayProps> = ({ ticket }) => {
  const chartData = [
    { name: 'Edge', value: ticket.mathematicalEdge },
    { name: 'Risk', value: 100 - ticket.mathematicalEdge }
  ];
  const COLORS = ['#10b981', '#334155'];

  const foldCount = ticket.matches.length;
  const isRollover = ticket.mode === AppMode.ROLLOVER;
  const potentialReturn = (1000 * ticket.totalOdds).toLocaleString(undefined, { maximumFractionDigits: 0 });

  return (
    <div className="w-full grid grid-cols-1 lg:grid-cols-3 gap-6 animate-fade-in-up">
      
      {/* Main Ticket */}
      <div className="lg:col-span-2 space-y-4">
        <div className="bg-white dark:bg-slate-850 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden shadow-2xl transition-colors duration-300">
          {/* Ticket Header */}
          <div className="bg-slate-50 dark:bg-slate-900/50 p-6 border-b border-slate-200 dark:border-slate-800 flex flex-col md:flex-row justify-between items-start md:items-center transition-colors duration-300 gap-4">
            <div>
              <div className="flex items-center space-x-2 mb-1">
                 <span className="text-xs font-mono text-emerald-600 dark:text-emerald-500 px-2 py-1 bg-emerald-500/10 rounded border border-emerald-500/20 uppercase flex items-center">
                    <Layers className="w-3 h-3 mr-1" />
                    {ticket.strategyName}
                 </span>
                 <span className="text-xs font-mono text-purple-600 dark:text-purple-400 px-2 py-1 bg-purple-500/10 rounded border border-purple-500/20 uppercase flex items-center">
                    <Sigma className="w-3 h-3 mr-1" />
                    {foldCount}-Fold Acca
                 </span>
              </div>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-2 flex items-baseline transition-colors duration-300">
                <span className="text-sm text-slate-500 dark:text-slate-400 mr-2 font-mono font-normal uppercase">Accumulator Odds:</span>
                <span className="text-emerald-600 dark:text-emerald-400 font-mono">{ticket.totalOdds.toFixed(2)}</span>
              </h2>
            </div>
            
            {/* ROI Display */}
            <div className="flex items-center bg-emerald-500/5 border border-emerald-500/20 px-4 py-2 rounded-lg">
                <div className="mr-3 text-right">
                    <p className="text-[10px] text-slate-500 dark:text-slate-400 font-mono uppercase">Potential Return (₦1k Stake)</p>
                    <p className="text-lg font-bold text-emerald-600 dark:text-emerald-400 font-mono">₦{potentialReturn}</p>
                </div>
                <div className="bg-emerald-500 text-white p-2 rounded-md">
                    <Wallet className="w-5 h-5" />
                </div>
            </div>
          </div>

          {/* Special Rollover Instruction Banner */}
          {isRollover && (
             <div className="bg-amber-500/10 border-b border-amber-500/20 px-6 py-2 flex items-center space-x-3">
                 <Coins className="w-4 h-4 text-amber-500" />
                 <p className="text-xs font-mono font-bold text-amber-600 dark:text-amber-500 uppercase flex-1">
                     Harvest Protocol: Bank 50% of Profit. Reinvest Principal + 50% Profit only.
                 </p>
                 <Landmark className="w-4 h-4 text-amber-500" />
             </div>
          )}

          {/* Matches List */}
          <div className="divide-y divide-slate-200 dark:divide-slate-800">
            {ticket.matches.map((match, idx) => (
              <MatchItem key={idx} match={match} />
            ))}
          </div>
          
           <div className="p-4 bg-slate-50 dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 transition-colors duration-300">
             <p className="text-xs text-slate-500 text-center font-mono">
               GENERATED BY KINGBAYO WARLORD PROTOCOL • ID: {ticket.id.split('-')[0]}
             </p>
           </div>
        </div>
      </div>

      {/* Side Analytics */}
      <div className="lg:col-span-1 space-y-6">
        
        {/* Win Probability Donut */}
        <div className="bg-white dark:bg-slate-850 rounded-xl border border-slate-200 dark:border-slate-700 p-6 flex flex-col items-center justify-center relative shadow-xl transition-colors duration-300">
           <h3 className="text-sm font-mono uppercase text-slate-500 dark:text-slate-400 mb-4 tracking-widest text-center w-full border-b border-slate-200 dark:border-slate-800 pb-2">
              Mathematical Edge
           </h3>
           <div className="h-48 w-full relative">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={chartData}
                    cx="50%"
                    cy="50%"
                    innerRadius={60}
                    outerRadius={80}
                    fill="#8884d8"
                    paddingAngle={5}
                    dataKey="value"
                    stroke="none"
                  >
                    {chartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip 
                     contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', borderRadius: '8px' }}
                     itemStyle={{ color: '#e2e8f0' }}
                  />
                </PieChart>
              </ResponsiveContainer>
              {/* Center Text */}
              <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                <span className="text-3xl font-bold text-slate-900 dark:text-white transition-colors duration-300">{ticket.mathematicalEdge}%</span>
                <span className="text-[10px] text-slate-500 uppercase">Probability</span>
              </div>
           </div>
           <p className="text-xs text-slate-400 text-center mt-2">
              Algorithm Confidence Interval
           </p>
        </div>

        {/* Disclaimer / Info */}
        <div className="bg-amber-500/5 rounded-xl border border-amber-500/20 p-4">
           <div className="flex items-start space-x-3">
              <ShieldAlert className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
              <div>
                 <h4 className="text-sm font-bold text-amber-600 dark:text-amber-500 uppercase mb-1">Acca Math</h4>
                 <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                    This ticket relies on the combined probability of all {foldCount} legs. If one leg fails, the accumulator fails. The "Mathematical Edge" represents the estimated probability of the entire chain holding.
                 </p>
              </div>
           </div>
        </div>

      </div>
    </div>
  );
};

const MatchItem: React.FC<{ match: MatchSelection }> = ({ match }) => {
  return (
    <div className="p-4 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors duration-200 group">
      <div className="flex justify-between items-start mb-2">
        <div className="flex items-center space-x-2 flex-wrap gap-y-1">
           {match.isLive ? (
             <span className="animate-pulse bg-red-500 text-white text-[10px] font-bold px-1.5 py-0.5 rounded uppercase">
               LIVE
             </span>
           ) : (
             <span className="bg-slate-200 dark:bg-slate-700 text-slate-600 dark:text-slate-300 text-[10px] font-bold px-1.5 py-0.5 rounded uppercase flex items-center transition-colors duration-300">
               <Clock className="w-3 h-3 mr-1" /> {match.time}
             </span>
           )}
           <span className="bg-slate-100 dark:bg-slate-800 text-emerald-600 dark:text-emerald-400 text-[10px] font-bold px-1.5 py-0.5 rounded uppercase border border-slate-200 dark:border-slate-700 transition-colors duration-300">
              {match.sport}
           </span>
           <span className="text-xs text-slate-500 dark:text-slate-400 flex items-center">
             <MapPin className="w-3 h-3 mr-1" /> {match.league}
           </span>
        </div>
        <div className="text-right">
           <span className="block text-emerald-600 dark:text-emerald-400 font-bold font-mono bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20">
             @{match.odds.toFixed(2)}
           </span>
        </div>
      </div>

      <div className="flex justify-between items-center mb-3">
         <div className="font-bold text-lg text-slate-900 dark:text-white transition-colors duration-300">
            {match.homeTeam} <span className="text-slate-400 dark:text-slate-500 text-sm font-normal">vs</span> {match.awayTeam}
         </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
           <p className="text-xs text-slate-500 uppercase mb-1">Market / Selection</p>
           <div className="flex items-center space-x-2">
              <span className="text-sm text-slate-600 dark:text-slate-300 transition-colors duration-300">{match.market}</span>
              <span className="text-slate-400 dark:text-slate-600">/</span>
              <span className="text-sm font-bold text-emerald-600 dark:text-emerald-300 transition-colors duration-300">{match.selection}</span>
           </div>
        </div>
        <div className="bg-slate-50 dark:bg-slate-900/50 p-3 rounded-lg border border-slate-200 dark:border-slate-700/50 transition-colors duration-300">
            <div className="flex items-center space-x-2 mb-1">
                <TrendingUp className="w-3 h-3 text-emerald-500" />
                <span className="text-[10px] font-mono uppercase text-emerald-600 dark:text-emerald-500">Warlord Reasoning</span>
            </div>
            <p className="text-xs text-slate-600 dark:text-slate-300 leading-tight italic transition-colors duration-300">
                "{match.reasoning}"
            </p>
        </div>
      </div>
      
      {/* Confidence Bar */}
      <div className="mt-3">
         <div className="flex justify-between text-[10px] text-slate-500 uppercase mb-1">
            <span>Confidence</span>
            <span>{match.confidence}%</span>
         </div>
         <div className="w-full bg-slate-200 dark:bg-slate-800 rounded-full h-1.5 transition-colors duration-300">
            <div 
              className="bg-emerald-500 h-1.5 rounded-full shadow-[0_0_10px_rgba(16,185,129,0.5)]" 
              style={{ width: `${match.confidence}%` }}
            ></div>
         </div>
      </div>

    </div>
  );
};

export default TicketDisplay;
